### ISSUE TITLE
Release 0.0.13

### ISSUE THREAD

**Issue by retr0h** [ManrajGrover/py-log-symbols#19]
Could we get 0.0.13 released?

## Description

Could we get 0.0.13 released.  I see that there were changes made to handle enum34, but this doesn't appear to be released. 

https://github.com/manrajgrover/py-log-symbols/commit/3e5528dfe794d45802b16f2f3e213b3794ea9d66#diff-b4ef698db8ca845e5845c4618278f29a

**Comment by adamtheturtle** [comment]
@manrajgrover - Is there something I can do to help with this?

**Comment by manrajgrover** [comment]
Really sorry for the delays. I'll have a look at this and make a release very soon.

**Comment by adamtheturtle** [comment]
Thank you @manrajgrover and no worries. My hope is that you could also update `halo` to use the new version once this is done.

**Comment by embray** [comment]
Thank you, and ditto @adamtheturtle on doing anything I can to help.

**Comment by juledwar** [comment]
I have the exact same requirement. I will have to remove Halo from my project unless we get this released soon :(

Thanks.

**Comment by manrajgrover** [comment]
@retr0h @embray @adamtheturtle @juledwar 

I apologize for the delay. I've been switching roles and didn't have access to computer or time to make this possible.

I've released [`v0.0.13`](https://pypi.org/project/log-symbols/0.0.13/) which should fix this. Can you please check now and confirm?

**Comment by juledwar** [comment]
Confirmed, thanks a bunch!

**Comment by manrajgrover** [comment]
Awesome! Closing this as it should be fixed now.
